### ISSUE TITLE
Show role when choosing database

### ISSUE THREAD

**Issue by slootjes** [whilenull/7777-support#54]
When using Port 7777 on an RDS cluster with multiple instances the output looks something like this:

```
Listing databases.
Which database would you like to connect to?

[1] some-service-databaseinstance1-azznqqajdhkm
[2] some-service-databaseinstance2-cqtwprntcl09
```

but based on this names I don't know which of the 2 is a reader or a writer. When making changes I obviously need a writer and while just doing some queries I prefer using a reader instance. Currently I always need to login to AWS to see which one I need. It would be very nice to see the role of the instance in this selection, perhaps like this:

```
Listing databases.
Which database would you like to connect to?

[1] some-service-databaseinstance1-azznoqajd0km (Writer instance)
[2] some-service-databaseinstance2-cqtwprbtdl09 (Reader instance)
```

While writing this, maybe also add the instance size to it as well:

```
Listing databases.
Which database would you like to connect to?

[1] some-service-databaseinstance1-azznoqajd0km (Writer instance / Serverless v2 (0.5 - 16 ACUs))
[2] some-service-databaseinstance2-cqtwprbtdl09 (Reader instance / tg4.medium)
```

What do you think?

**Comment by mnapoli** [comment]
Sounds like a great improvement idea, thanks for opening this. Naive question: is the reader/writer status exposed via the RDS API?

In any case I'm taking note of the idea (no promise on an implementation date ^^)

**Comment by slootjes** [comment]
The information is returned in the describe db clusters API endpoint which is already used as far as I know by this app, this is the relevant output for my cluster:

```
<DBClusterMembers>
	<DBClusterMember>
		<DBInstanceIdentifier>some-service-databaseinstance1-azznoqajd0km</DBInstanceIdentifier>
		<DBClusterParameterGroupStatus>in-sync</DBClusterParameterGroupStatus>
		<PromotionTier>1</PromotionTier>
		<IsClusterWriter>true</IsClusterWriter>
	</DBClusterMember>
	<DBClusterMember>
		<DBInstanceIdentifier>some-service-databaseinstance2-cqtwprbtdl09</DBInstanceIdentifier>
		<DBClusterParameterGroupStatus>in-sync</DBClusterParameterGroupStatus>
		<PromotionTier>1</PromotionTier>
		<IsClusterWriter>false</IsClusterWriter>
	</DBClusterMember>
</DBClusterMembers>
```

The "IsClusterWriter" returns the relevant information if it's read/write or read only.

The instance type is available in the Describe Db Instances API call:

```
<DBInstanceClass>db.serverless</DBInstanceClass>
```

Maybe returning it as a table would be prettier even when adding more information.

**Comment by slootjes** [comment]
Any update on this by any chance? The same thing applies for Elasticache:

```
Which Elasticache instance would you like to connect to?

[1] blr10bzer1fvecf1-001
[2] blr10bzer1fvecf1-002
[3] blrhen971d0ou3l-001
[4] blrhen971d0ou3l-002
```

Here it doesn't even show the name, only the identifier given by AWS. The same information would be useful here, especially the description and role (primary/replica).

**Comment by slootjes** [comment]
Any update on this by any chance? The same thing applies for Elasticache:

Which Elasticache instance would you like to connect to?

```
[1] blr12bzer1fbecf1-001
[2] blr12bzer1fbecf1-002
[3] blrhen961d1ou3l-001
[4] blrhen961d1ou3l-002
```

Here it doesn't even show the name, only the identifier given by AWS. The same information would be useful here, especially the description and role (primary/replica).

**Comment by slootjes** [comment]
Any news on this? Please let me know if there is a way for me to contribute, I don't think this should be difficult.

**Comment by mnapoli** [comment]
@slootjes no update at the moment.

Here is the relevant code if you want to have a go at it: https://gist.github.com/mnapoli/ea2300ed9496784ac91addefa183fd4f

The small challenge is that the prompt's selected result === what is displayed. So if we add more info to each line (e.g. the name, etc.), then when the user selects the line we get the whole string back.

**Comment by slootjes** [comment]
Thanks for this :) The easy way out would be to have something like "{option} - {extra usefull stuff}" and then split/trim on the - and use the first part?

**Comment by slootjes** [comment]
I do see that the cluster ID being such a random name is because the ID is optional in CloudFormation and I didn't set one, this is not a bug in Port 7777. It would be very nice though to also get the description (which I did fill in) but I understand if this is a problem of my own :) The reader/writer (or primary/replace) would be most useful to know still.

**Comment by slootjes** [comment]
Any way I can help with this? While I love this tool, this is still a major annoyance every time I need to connect with an instance.

**Comment by mnapoli** [comment]
Hey @slootjes! I've published v1.1.20 (it should be available in a few minutes once the build finishes). I tried to add more details, the writer/reader was a bit trickier so I went with other options. This isn't perfect, but I hope it will help identify a bit better the right cluster.

Please let me know if that helps!

**Comment by slootjes** [comment]
Hey @mnapoli I see the update and it now renders this for me:

```
Which database would you like to connect to?

[1] <stack_name>-databaseinstance1-<id> (instance - aurora-postgresql - db.serverless)
[2] <stack_name>-databaseinstance2-<id> (instance - aurora-postgresql - db.serverless)
```
and while this is progress (thanks!), it doesn't solve my issue since I still don't know which database I need to select...

I'm really happy to help out here, let me know.

**Comment by mnapoli** [comment]
😢 ok at least we can iterate now! What fields should I render there to make it more useful?

FYI I have a [DBCluster object](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DBCluster.html) (result of DescribeDBClusters), which field should I use instead?

**Comment by slootjes** [comment]
That API call returns me:

```
"DBClusterMembers": [
	{
		"DBInstanceIdentifier": "<stack>-databaseinstance1-<id>",
		"IsClusterWriter": false,
		"DBClusterParameterGroupStatus": "in-sync",
		"PromotionTier": 1
	},
	{
		"DBInstanceIdentifier": "<stack>-databaseinstance2-<id>",
		"IsClusterWriter": true,
		"DBClusterParameterGroupStatus": "in-sync",
		"PromotionTier": 1
	}
],
```

so the `"IsClusterWriter"": false` would result in "Read" and `"IsClusterWriter": true` in "Read/Write". The naming is up for debate of course.

**Comment by mnapoli** [comment]
If there are multiple `DBClusterMembers` which do you want to be used for the label? The first one in the list?

**Comment by slootjes** [comment]
I think the label is good as-is, for RDS at least 👍  For ElastiCache it's still showing me:
```
[1] blr12bzer1fbecf1-001
[2] blr12bzer1fbecf1-002
[3] blrhen961d1ou3l-001
[4] blrhen961d1ou3l-002
```

Could you list me the API calls you do for this too? Then I can have a look at the output theretoo.

**Comment by mnapoli** [comment]
For ElastiCache this would be: https://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/API_DescribeCacheClusters.html#API_DescribeCacheClusters_ResponseElements 

I.e. https://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/API_CacheCluster.html

**Comment by slootjes** [comment]
It seems that unfortunately for ElastiCache, the primary/replica information is not available in that API call. It is available in https://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/API_DescribeReplicationGroups.html though but I can image this is more work to implement (--use-replication-group). For thought, here is the (relevant) API response for one of my replication groups:

```
{
	"ReplicationGroupId": "clr8uavmkf12zl5",
	"Description": "my-cluster-desription",
	"NodeGroups": [
		{
			"NodeGroupId": "0001",
			"Status": "available",
			"PrimaryEndpoint": {
				"Address": "master.clr8uavmkf12zl5.eyw9.euw1.cache.amazonaws.com",
				"Port": 6379
			},
			"ReaderEndpoint": {
				"Address": "replica.clr8uavmkf12zl5.eyw9.euw1.cache.amazonaws.com",
				"Port": 6379
			},
			"NodeGroupMembers": [
				{
					"CacheClusterId": "clr8uavmkf12zl5-001",
					"CacheNodeId": "0001",
					"ReadEndpoint": {
						"Address": "clr8uavmkf12zl5-001.clr8uavmkf12zl5.eyw9.euw1.cache.amazonaws.com",
						"Port": 6379
					},
					"PreferredAvailabilityZone": "eu-west-1a",
					"CurrentRole": "replica"
				},
				{
					"CacheClusterId": "clr8uavmkf12zl5-002",
					"CacheNodeId": "0001",
					"ReadEndpoint": {
						"Address": "clr8uavmkf12zl5-002.clr8uavmkf12zl5.eyw9.euw1.cache.amazonaws.com",
						"Port": 6379
					},
					"PreferredAvailabilityZone": "eu-west-1b",
					"CurrentRole": "primary"
				}
			]
		}
	],
}
```
where this output would be ideal:

`[0] <ReplicationGroupId> <(Description, if set)> - <CacheClusterId> - <CurrentRole>`
etc

so in my case it would look like this:
```
[0] clr8uavmkf12zl5 (my-cluster-desription) - clr8uavmkf12zl5-001 - replica
[1] clr8uavmkf12zl5 (my-cluster-desription) - clr8uavmkf12zl5-001 - primary
```

I can imagine this is a lot of work and out of scope since it's hard to do without a BC break or adding new parameters). Again, happy to help but currently I can't since it's closed source.

**Comment by mnapoli** [comment]
Right, this is a bit more work in that case, I'd prefer to leave this aside for now 👍

**Comment by slootjes** [comment]
1. Could you still look into the `IsClusterWriter` variable for RDS as mentioned earlier? this should be available already in the data you have.
2. No options for me to help on the Elasticache thing? Happy to sign an NDA of some kind if needed.

**Comment by mnapoli** [comment]
1. yes but what about this https://github.com/whilenull/7777-support/issues/54#issuecomment-2976512465 ? Because it seems like it's not just a field, it's inside a list
2. [just like I did previously for DB](https://github.com/whilenull/7777-support/issues/54#issuecomment-2459039693), here's the code: https://gist.github.com/mnapoli/dd86649a684f1c67ae26c0999f2a6daa (you can see that the Selector class accepts an optional list of labels, you can pass extra labels via this and it should work), if you have a diff I can try it out 👍

**Comment by slootjes** [comment]
1. When I call the rds describe-db-clusters API, it returns me 1 cluster which consists of 2 members and I can choose from both members in Port7777. My assumption is that it is currently looping over those to generate the list; _IsClusterWriter_ is part of those objects so I think it should be available to render as part of the name. I do not see this code in the gist though.

2. Thanks, I will have a look.
